// This file is auto-generated by @hey-api/openapi-ts


import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { $OpenApiTs } from './types.gen';

export class BlockPreviewService {
    /**
 * @returns string Success
 * @throws ApiError
 */
    public static postUmbracoBlockpreviewApiV1PreviewGridMarkup(data: $OpenApiTs['/umbraco/blockpreview/api/v1/previewGridMarkup']['post']['req'] = {}): CancelablePromise<$OpenApiTs['/umbraco/blockpreview/api/v1/previewGridMarkup']['post']['res'][200]> {
        const { pageId, blockEditorAlias, culture, requestBody } = data;
        return __request(OpenAPI, {
    method: 'POST',
    url: '/umbraco/blockpreview/api/v1/previewGridMarkup',
    query: {
        pageId,
        blockEditorAlias,
        culture
    },
    body: requestBody,
    mediaType: 'application/json'
});
    }
    
    /**
 * @returns string Success
 * @throws ApiError
 */
    public static postUmbracoBlockpreviewApiV1PreviewListMarkup(data: $OpenApiTs['/umbraco/blockpreview/api/v1/previewListMarkup']['post']['req'] = {}): CancelablePromise<$OpenApiTs['/umbraco/blockpreview/api/v1/previewListMarkup']['post']['res'][200]> {
        const { pageId, blockEditorAlias, culture, requestBody } = data;
        return __request(OpenAPI, {
    method: 'POST',
    url: '/umbraco/blockpreview/api/v1/previewListMarkup',
    query: {
        pageId,
        blockEditorAlias,
        culture
    },
    body: requestBody,
    mediaType: 'application/json'
});
    }
    
}