// This file is auto-generated by @hey-api/openapi-ts


export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type $OpenApiTs = {
    '/umbraco/blockpreview/api/v1/previewGridMarkup': {
        post: {
            req: {
                blockEditorAlias?: string;
                culture?: string;
                pageKey?: string;
                requestBody?: string;
            };
            res: {
                /**
 * Success
 */
                200: string;
            };
        };
    };
    '/umbraco/blockpreview/api/v1/previewListMarkup': {
        post: {
            req: {
                blockEditorAlias?: string;
                culture?: string;
                pageKey?: string;
                requestBody?: string;
            };
            res: {
                /**
 * Success
 */
                200: string;
            };
        };
    };
};