// This file is auto-generated by @hey-api/openapi-ts


export type BlockGridLayoutAreaItemModel = {
    key: string;
    items: Array<(BlockGridLayoutItemModel)>;
};

export type BlockGridLayoutItemModel = {
    contentUdi?: UdiModel | null;
    settingsUdi?: UdiModel | null;
    columnSpan?: number | null;
    rowSpan?: number | null;
    areas: Array<(BlockGridLayoutAreaItemModel)>;
};

export type BlockItemDataModel = {
    contentTypeKey: string;
    udi?: UdiModel | null;
    [key: string]: (unknown) | undefined;
};

export type BlockListLayoutItemModel = {
    contentUdi?: UdiModel | null;
    settingsUdi?: UdiModel | null;
};

export type BlockValueBlockGridLayoutItemModel = {
    layout: {
        [key: string]: Array<(BlockGridLayoutItemModel)>;
    };
    contentData: Array<(BlockItemDataModel)>;
    settingsData: Array<(BlockItemDataModel)>;
};

export type BlockValueBlockListLayoutItemModel = {
    layout: {
        [key: string]: Array<(BlockListLayoutItemModel)>;
    };
    contentData: Array<(BlockItemDataModel)>;
    settingsData: Array<(BlockItemDataModel)>;
};

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type UdiModel = {
    readonly uriValue: string;
    readonly entityType: string;
    readonly isRoot: boolean;
};

export type $OpenApiTs = {
    '/umbraco/blockpreview/api/v1/previewGridMarkup': {
        post: {
            req: {
                blockEditorAlias?: string;
                culture?: string;
                pageId?: number;
                requestBody?: BlockValueBlockGridLayoutItemModel;
            };
            res: {
                /**
 * Success
 */
                200: string;
            };
        };
    };
    '/umbraco/blockpreview/api/v1/previewListMarkup': {
        post: {
            req: {
                blockEditorAlias?: string;
                culture?: string;
                pageId?: number;
                requestBody?: BlockValueBlockListLayoutItemModel;
            };
            res: {
                /**
 * Success
 */
                200: string;
            };
        };
    };
};